"use client";

import { useState } from "react";
import { OutliveButton } from "@/components/ui/OutliveButton";

export function InsightsContent() {
  const [question, setQuestion] = useState("");
  const [includeBloodwork, setIncludeBloodwork] = useState(true);
  const [includeWearables, setIncludeWearables] = useState(true);
  const [includeGenomics, setIncludeGenomics] = useState(true);
  const [insights, setInsights] = useState<string[]>([]);
  const [model, setModel] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  async function handleGenerate() {
    setLoading(true);
    setError(null);
    setInsights([]);
    setModel(null);

    try {
      const res = await fetch("/api/backend/ai/insights", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          context: {
            include_bloodwork: includeBloodwork,
            include_wearables: includeWearables,
            include_genomics: includeGenomics,
          },
          ...(question.trim() ? { question: question.trim() } : {}),
        }),
      });

      if (!res.ok) throw new Error("Failed to generate insights");

      const data = await res.json();
      setInsights(data.insights || []);
      setModel(data.model || null);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to generate insights");
    } finally {
      setLoading(false);
    }
  }

  return (
    <div className="space-y-[var(--space-lg)]">
      {/* Question input */}
      <div className="bg-card rounded-[var(--radius-md)] border border-[var(--surface-elevated)] p-[var(--space-lg)] space-y-[var(--space-md)]">
        <div>
          <label className="block text-sm text-muted mb-1">Question</label>
          <textarea
            value={question}
            onChange={(e) => setQuestion(e.target.value)}
            placeholder="Ask about your health data..."
            rows={3}
            className="w-full p-2 bg-[var(--surface-secondary)] border border-[var(--surface-elevated)] rounded-[var(--radius-sm)] text-foreground resize-y"
          />
        </div>

        {/* Context toggles */}
        <div>
          <label className="block text-sm text-muted mb-2">Include data from:</label>
          <div className="flex flex-wrap gap-x-[var(--space-lg)] gap-y-[var(--space-xs)]">
            <label className="flex items-center gap-2 text-foreground cursor-pointer">
              <input
                type="checkbox"
                checked={includeBloodwork}
                onChange={(e) => setIncludeBloodwork(e.target.checked)}
                className="accent-[var(--training)]"
              />
              Bloodwork
            </label>
            <label className="flex items-center gap-2 text-foreground cursor-pointer">
              <input
                type="checkbox"
                checked={includeWearables}
                onChange={(e) => setIncludeWearables(e.target.checked)}
                className="accent-[var(--training)]"
              />
              Wearables
            </label>
            <label className="flex items-center gap-2 text-foreground cursor-pointer">
              <input
                type="checkbox"
                checked={includeGenomics}
                onChange={(e) => setIncludeGenomics(e.target.checked)}
                className="accent-[var(--training)]"
              />
              Genomics
            </label>
          </div>
        </div>

        <OutliveButton onClick={handleGenerate} loading={loading}>
          Generate Insights
        </OutliveButton>
      </div>

      {/* Error */}
      {error && (
        <div className="bg-card rounded-[var(--radius-md)] border border-recovery-red p-[var(--space-md)]">
          <p className="text-recovery-red text-sm">{error}</p>
        </div>
      )}

      {/* Results */}
      {insights.length > 0 && (
        <div className="space-y-[var(--space-sm)]">
          {model && (
            <p className="text-xs text-muted">Generated by {model}</p>
          )}
          {insights.map((insight, i) => (
            <div
              key={i}
              className="bg-card rounded-[var(--radius-md)] border border-[var(--surface-elevated)] p-[var(--space-md)]"
            >
              <p className="text-foreground whitespace-pre-wrap">{insight}</p>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
