name: OutliveEngine
options:
  bundleIdPrefix: com.outlive-engine
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
  createIntermediateGroups: true
  generateEmptyDirectories: false
  groupSortPosition: top

settings:
  base:
    SWIFT_VERSION: "6.0"
    SWIFT_STRICT_CONCURRENCY: complete
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Automatic

targets:
  OutliveEngine:
    type: application
    platform: iOS
    sources:
      - path: OutliveEngine
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.outlive-engine.app
        INFOPLIST_GENERATION_MODE: GeneratedFile
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: true
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: true
        INFOPLIST_KEY_UILaunchScreen_Generation: true
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_CFBundleDisplayName: "Outlive Engine"
        INFOPLIST_KEY_NSHealthShareUsageDescription: "Outlive Engine reads your health data to personalize your daily protocols, track recovery, and optimize training recommendations."
        INFOPLIST_KEY_NSHealthUpdateUsageDescription: "Outlive Engine records body composition measurements and workout data to your Health app."
        INFOPLIST_KEY_NSFaceIDUsageDescription: "Outlive Engine uses Face ID to protect your encrypted health data."
        INFOPLIST_KEY_NSCameraUsageDescription: "Outlive Engine uses the camera to scan bloodwork lab reports via OCR."
        INFOPLIST_KEY_NSPhotoLibraryUsageDescription: "Outlive Engine accesses your photo library to import bloodwork lab report images."
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ENABLE_PREVIEWS: true
        SWIFT_EMIT_LOC_STRINGS: true
    entitlements:
      path: OutliveEngine/OutliveEngine.entitlements
      properties:
        com.apple.developer.healthkit: true
        com.apple.developer.healthkit.access:
          - health-records
        com.apple.developer.applesignin:
          - Default
        com.apple.developer.associated-domains:
          - "applinks:api.outlive.app"
        com.apple.security.application-groups:
          - "group.com.outlive-engine.app"
        com.apple.developer.default-data-protection: NSFileProtectionCompleteUntilFirstUserAuthentication
    preBuildScripts: []
    postBuildScripts: []

  OutliveEngineTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: OutliveEngineTests
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.outlive-engine.tests
        INFOPLIST_GENERATION_MODE: GeneratedFile
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/OutliveEngine.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/OutliveEngine"
        BUNDLE_LOADER: "$(TEST_HOST)"
    dependencies:
      - target: OutliveEngine

schemes:
  OutliveEngine:
    build:
      targets:
        OutliveEngine: all
        OutliveEngineTests: [test]
    run:
      config: Debug
      simulateLocation: false
    test:
      config: Debug
      gatherCoverageData: true
      targets:
        - OutliveEngineTests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
