// DailyProtocol.swift
// OutliveEngine
//
// The daily action plan generated by the protocol engine, covering training,
// nutrition, supplements, interventions, and sleep.

import Foundation
import SwiftData

@Model
final class DailyProtocol: Sendable {

    var userId: String
    var date: Date
    var recoveryZone: RecoveryZone

    // MARK: - Stored as JSON Data

    private var trainingData: Data?
    private var nutritionData: Data?
    private var supplementsData: Data?
    private var interventionsData: Data?
    private var sleepData: Data?

    var training: TrainingBlock? {
        get { try? JSONDecoder().decode(TrainingBlock.self, from: trainingData ?? Data()) }
        set { trainingData = try? JSONEncoder().encode(newValue) }
    }

    var nutrition: NutritionPlan? {
        get { try? JSONDecoder().decode(NutritionPlan.self, from: nutritionData ?? Data()) }
        set { nutritionData = try? JSONEncoder().encode(newValue) }
    }

    var supplements: [SupplementDose] {
        get { (try? JSONDecoder().decode([SupplementDose].self, from: supplementsData ?? Data())) ?? [] }
        set { supplementsData = try? JSONEncoder().encode(newValue) }
    }

    var interventions: [InterventionBlock] {
        get { (try? JSONDecoder().decode([InterventionBlock].self, from: interventionsData ?? Data())) ?? [] }
        set { interventionsData = try? JSONEncoder().encode(newValue) }
    }

    var sleep: SleepProtocol? {
        get { try? JSONDecoder().decode(SleepProtocol.self, from: sleepData ?? Data()) }
        set { sleepData = try? JSONEncoder().encode(newValue) }
    }

    // MARK: - Adherence

    /// Adherence score normalized to 0–100.
    var adherenceScore: Double?
    var notes: String?

    // MARK: - Metadata

    var syncStatus: SyncStatus
    var generatedAt: Date

    // MARK: - Init

    init(
        userId: String,
        date: Date,
        recoveryZone: RecoveryZone,
        training: TrainingBlock? = nil,
        nutrition: NutritionPlan? = nil,
        supplements: [SupplementDose] = [],
        interventions: [InterventionBlock] = [],
        sleep: SleepProtocol? = nil,
        adherenceScore: Double? = nil,
        notes: String? = nil,
        syncStatus: SyncStatus = .pending,
        generatedAt: Date = .now
    ) {
        self.userId = userId
        self.date = date
        self.recoveryZone = recoveryZone
        self.trainingData = try? JSONEncoder().encode(training)
        self.nutritionData = try? JSONEncoder().encode(nutrition)
        self.supplementsData = try? JSONEncoder().encode(supplements)
        self.interventionsData = try? JSONEncoder().encode(interventions)
        self.sleepData = try? JSONEncoder().encode(sleep)
        self.adherenceScore = adherenceScore
        self.notes = notes
        self.syncStatus = syncStatus
        self.generatedAt = generatedAt
    }
}
